### ISSUE TITLE
fltk

### ISSUE THREAD

**Issue by grammoboy2** [Stazed/non-timeline-xt#3]
Just curious, why the port to fltk? I think some of ntk's visual/ speed optimizations can't be done in fltk, cause it would break backward compatibility, which is not allowed in the fltk project afaik. The current maintainer of fltk walked trough every commit of ntk two years ago I think, and saw them as reasonable from the perspective of the goals of ntk. 

Ntk is based on a older version of fltk, but the question is whether new upgrades in fltk will benefit the non-suite. Most notably there is now Fl_Grid and Fl_Flex, I can imagine these could be beneficial for non-sequencer, but I'm not sure.

Ntk includes cairo right? I think the fltk developers where comparing cairo with x11 two years ago or so, no idea what developments are in this area. 

The maintainer of fltk is quite open for suggestions of features of ntk which can be backported to fltk by the way, but not if it breaks backward compatibility.

**Comment by Stazed** [comment]
> Just curious, why the port to fltk?

I looks better (clearer) to me.

If you prefer the NTK look, you can still build this project with NTK as indicated in the README.md

**Comment by grammoboy2** [comment]
It's nice to have those build options, same for non-mixer-xt to leave out extra support for plugin formats.

I find the look of non-daw one of the prettiest when looking for fltk based applications. Giada and yoshimi do a decent job as well. The latter has done a very good job to make some clear contrasts, but I wonder if it is fltk vs ntk or just some theme / color finetuning.

**Comment by M0JXD** [comment]
I've been playing with the NTK builds. I've found Non-XT's build is missing some of the "beauty" of the original non, you can see here the playback cursor in the vector style doesn't have the same transparency effect:

![NTK-Build-Missing-Vector-Beauty](https://github.com/user-attachments/assets/26d89b42-9816-42c9-857d-51d2059c6edf)

Also the SEEK/SOLO/SEL/REC buttons seem to be quite longer in XT. 

As an aside would you consider hosting a repo with NTK fixes (so everything Non-XT is under one account), to build NTK I had to update waf as the module 'imp' is not in the latest python. I'm not sure if you're interested in adding the vector and cairo styles to the FLTK build? I know you prefer FLTK's clearer look but I quite like them :)

Thanks so much.

**Comment by Stazed** [comment]
When JML left, since he did not grant anyone the rights to continue the original projects, he effectively killed them. This includes NTK. The only way to continue them is to fork, change the name, etc without violating the GPL. You cannot even update or maintain them as the original.  This makes trying to continue with NTK a real hassle and breaks backward compatibility of all projects based on it. In short, it is much more trouble than it is worth to me.

For me, the differences between FLTK and NTK are superficial and cosmetic and FLTK works well enough for me. I did not say that FLTK was prettier than NTK, just that the clearer look is easier for me to see when working on details, whereas the transparencies of NTK, I have found to be a hindrance.  I have no desire to revive NTK, and it appears that no one else does either...

**Comment by M0JXD** [comment]
Annoyingly Tuxfamily hosting is down (again) but on the [wayback machine](https://web.archive.org/web/20240501233458/http://non.tuxfamily.org/wiki/NtkPatches) the only other software aside from Non using NTK seems to be ZynAddSubFX, who have now changed to Zyn-Fusion with a Ruby UI, and SpiralSynthModular which is on a indefinite hiatus. I see some others like fabla, infamousplugins, sorcer and luppp that would probably appreciate some maintenance but are not under aggressive development and could probably switch to a fork with minimal difficulty.

I don't think the GPL requires renaming? Many distributions apply distro specific patches without renaming, and this doesn't violate the GPL. As far as I can tell the "only" requirement as a maintainer/contributor/forker is that you add your name to the license (Which you've done under your Stazed pseudonym) and some form of notice (renaming seems adequate in your case) to make it clear that it's modified. The FSF understand that situations like this are an issue in the FAQ:

> [Some have proposed alternatives to the GPL that require modified versions to go through the original author. As long as the original author keeps up with the need for maintenance, this may work well in practice, but if the author stops (more or less) to do something else or does not attend to all the users' needs, this scheme falls down. Aside from the practical problems, this scheme does not allow users to help each other. Sometimes control over modified versions is proposed as a means of preventing confusion between various versions made by users. In our experience, this confusion is not a major problem. Many versions of Emacs have been made outside the GNU Project, but users can tell them apart. The GPL requires the maker of a version to place his or her name on it, to distinguish it from other versions and to protect the reputations of other maintainers. ](https://www.gnu.org/licenses/old-licenses/gpl-2.0-faq.en.html#TOCWhyDoesTheGPLPermitUsersToPublishTheirModifiedVersions)

The only thing I see in the GPL possibly related is this:

> a) You must cause the modified files to carry prominent notices
    stating that you changed the files and the date of any change.

The renaming issue seems to be more in respect to [trademarks](https://help.author.envato.com/hc/en-us/articles/360000473263-Guidelines-for-forking-GPL-code) and good manners (I'm sure you've seen why JML left the scene... ). I don't believe Non-DAW is trademarked? I'll have to do some more research to be certain that this is the case with renaming GPL projects though.

However the other part to this is that you do not wish to maintain NTK for technical reasons, which is completely understandable. Nonetheless will you continue to develop Non-XT in a way that NTK can be used? There is clear desire for it as you have had this issue opened, and I see a few people in the Mixer's issue tracker have been building with NTK. I'd also be interested to know if the loss of transparency effects is due to the lack of NTK maintenance or Non-XT's usage of the toolkit?

I'd be interested in contributing to it and taking responsibility for non-compliance (if any). I have other programming projects on my plate at this time so it would not be immediate, maybe some time next year. I presume the big thing causing issues for your development is API discrepancies between NTK and the latest FLTK? No doubt Wayland is an issue as well. It's probably also worth changing the build system.

I think for a library, continued maintenance under the same name would be less a problem than what happened with NSM, plus their were other aspects to that than just the naming. If I take on NTK and @original-male asks for a name change I'd be happy to oblige, after all not much seems to depend on it anyways. Those that do use NTK are going to need toolkit maintenance eventually, especially with Wayland around the corner. I can contact distro package maintainers (as far as I can see that is only Fedora, Arch and openSUSE) and projects that use NTK to get their thoughts.

**Comment by Stazed** [comment]
> ...will you continue to develop Non-XT in a way that NTK can be used? 

Yes, provided that is does not become an over complicated maintenance nightmare. This should not be a problem as long as there are no major changes that deviate from FLTK. I am sure that many people would love to see NTK continue, and if you were willing to take it on, it would be greatly appreciated.

**Comment by grammoboy2** [comment]
Or apply the NTK improvements on the more recent fltk 1.4. That would probably require quite some work though and then I certainly would discuss it with the fltk maintainer first about the best approach here.

**Comment by M0JXD** [comment]
> I'd also be interested to know if the loss of transparency effects is due to the lack of NTK maintenance or Non-XT's usage of the toolkit?

Having just rebuilt original non from source (using a CXXFLAG for C++11 so Sequencer will build), it seems that the loss of transparency in the vector theme was done by JML himself after the [Debian packages on KXStudio](https://kx.studio/Repositories:Applications) were released, and are not a due to your changes or lack of maintenance on the toolkit: https://github.com/falkTX/ntk/commits/master/src/Vector_Theme.cxx

![image](https://github.com/user-attachments/assets/1f0da76b-732a-4dc1-88a6-1318c4b140bb)
