### ISSUE TITLE
Playhead to mouse context menu rarely works correctly

### ISSUE THREAD

**Issue by M0JXD** [Stazed/non-timeline-xt#8]
As mentioned in issue #7 I have this issue, the playback cursor does not go to the original click position of the context menu, often not moving at all:

![playbackcursor](https://github.com/user-attachments/assets/04a9d3b6-f5bb-477e-83fb-a94fef767099)

I'm using Linux Mint 22 Cinnamon, here's neofetch:

OS: Linux Mint 22 x86_64 
Host: Nitro AN515-57 V1.19 
Kernel: 6.8.0-49-generic 
Uptime: 14 hours, 5 mins 
Packages: 3428 (dpkg), 67 (flatpak) 
Shell: bash 5.2.21 
Resolution: 1920x1080 
DE: Cinnamon 6.2.9 
WM: Mutter (Muffin) 
WM Theme: Mint-Y-Dark-Sand (Mint-Y) 
Theme: Mint-Y-Dark-Sand [GTK2/3] 
Icons: Mint-Y-Sand [GTK2/3] 
Terminal: gnome-terminal 
CPU: 11th Gen Intel i7-11800H (16) @ 
GPU: NVIDIA GeForce RTX 3050 Ti Mobi 
GPU: Intel TigerLake-H GT1 [UHD Grap 
Memory: 4510MiB / 15767MiB 

Thanks

**Comment by Stazed** [comment]
I think you are misunderstanding how the "Playhead to mouse   P" is supposed to work. The idea is to position the mouse pointer on the timeline then hit the 'p' key. The playhead will then move to the mouse position on the timeline. By selecting from the menu, the mouse is captured by the popup, so no mouse position is available. In this case, actually selecting the menu item will not work and is shown for informational purposes only.

**Comment by M0JXD** [comment]
That's generally how I use it - I thought the context menu should work too but if it's just for informational purposes that's great as well. In that case maybe you could add "Edit from mouse selection 'r'" and "Select region 'Ctrl-Click'" to the menus too? Saves having to refer to the manual.

Thank you :)

**Comment by dannye** [comment]
You could easily fix this by recording the X/Y position of the mouse at the time that the context menu is opened, and use those coordinates if/when "Playhead to mouse" is selected.
(Why would a user ever assume a menu option will never work and is not meant to be selected?)

**Comment by Stazed** [comment]
> (Why would a user ever assume a menu option will never work and is not meant to be selected?)

Well I misspoke, the menu does work, you just cannot select the menu item with the mouse and would have to navigate the menu with keyboard while pointing the mouse outside the menu.

> You could easily fix this by recording the X/Y position of the mouse at the time that the context menu is opened

Since I am not the original author of this project and am still learning how it works, nothing is easy for me. It would probably take me an hour just to find the exact location to record the X/Y position, and another hour figuring out how to implement it, and another hour testing to make sure I did not break anything... but if it is easy for you, send me a PR. Which would probably take me an hour to review, but would save me some time... Seriously, using the "p" is the way it was meant to be used.

**Comment by Stazed** [comment]
Well it only took an hour because the XY position was already being recorded but was not being used for this menu item.
Sometimes you get lucky. Fixed in wip branch.

**Comment by M0JXD** [comment]
Commented on your commit about 5 mins ago, built it and it works great! Thank you.

**Comment by dannye** [comment]
Awesome! Nice work.
